### ISSUE TITLE
impulse~ bug

### ISSUE THREAD

**Issue by porres** [electrickery/pd-sigpack#1]
howdy, I have a bug issue with impulse~, the "0" phase doesn't really jump to the impulse

> For bugs found in this version, please report them to me. Martin is not responsible for bugs introduced by me.

Yeah, this is an old bug... should I reach Martin about this bug? Is he still responsible for fixing them?

cheers

**Comment by electrickery** [comment]
Hi, 

Thanks for reporting the issue. It appears the float isn't setting the phase of the signal, but controls the width of the impulse. This is a problem in the help-patch. 
The pulse width is however applied only once, then reverts to a single sample. This is a issue with the object.
As accurately controlling the phase of a signal with a message is not possible, controlling the pulse width is a reasonable usage of the float inlet.

The object is derived from a LADSPA plugin, I'll try deciphering how this is supposed to work
(https://github.com/swh/ladspa/blob/master/impulse_1885.xml).

**Comment by porres** [comment]
actually, seems like it is the phase indeed... much like phasor~

 if you give it 0.5, it's at half the cycle

but the impulse is coming at phase "1" (which was supposed to be the same as "0", but it is not)

if you instantiate the object at a low frequency of, say, 1hz, you'll see that it waits for a whole period before a sample is triggered, it's like it waits til it reaches "1"

so seems to me that the issue is because the trigger point is not at phase "0" but at phase "1"

**Comment by electrickery** [comment]
The original code at github looks exeactly like impulse~. I created an impulse2~ object with the expected behaviour (right-inlet 0 is phase 0) in branch "impulse2". Will think a bit on integrating this with sigpack and keeping it backward compatible. Maybe adding warning to the help-patch and a sub-patch with [- 1] - [* -1] is the simplest way.

**Comment by porres** [comment]
> The original code at github looks exeactly like impulse~

you mean the original from the earlier sigpack version?

> Will think a bit on integrating this with sigpack and keeping it backward compatible.

you mean creating an extra object or just updating/fixing the object?

thanks
